
name: Laravel

on:
  push:
    branches: [ "staging" ]


jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
     - name: Deploy Addval Application
       uses: appleboy/ssh-action@v0.1.2
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /opt/laravel/test # navigate into the folders
          git pull
          
