
name: Laravel

on:
  push:
    branches: [ "main" ]


jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
        
     - name: Get Github action IP
       id: ip
       uses: haythem/public-ip@v1.2
       
     - name: Setting environment variables..
       run: |
        echo "AWS_DEFAULT_REGION=ap-south-1" &gt;&gt; $GITHUB_ENV
        echo "AWS_SG_ID=sg-00e4eab7f7c3b961b" &gt;&gt; $GITHUB_ENV
        
     - name: Add Github Actions IP to Security group
       run: |
        aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
       env:
        SSH_ACCESSKEY: ${{ secrets.SSH_ACCESSKEY }}
        SSH_SECRETKEY: ${{ secrets.SSH_SECRETKEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      
     - name: Deploy Addval Application
       uses: appleboy/ssh-action@v0.1.2
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /opt/laravel/test # navigate into the folders
          sudo touch example.txt
          
     -  name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
         SSH_ACCESSKEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
         SSH_SECRETKEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
         if: always()
          
